# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=10)),
                ('diagnosis_code', models.CharField(blank=True, max_length=10, null=True)),
                ('full_code', models.CharField(max_length=50)),
                ('abbreviated_desc', models.CharField(max_length=125)),
                ('full_desc', models.CharField(max_length=255)),
                ('category_title', models.CharField(max_length=125)),
                ('icd_version', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
